# Generated by Django 4.2.9 on 2024-01-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slider', '0002_alter_slider_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(max_length=500, upload_to='uploads/slider/'),
        ),
    ]
