# Generated by Django 4.2.9 on 2024-01-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slider', '0003_alter_slider_slider_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
