# Generated by Django 4.2.9 on 2024-01-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0003_alter_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category_id',
            new_name='category',
        ),
    ]
