# Generated by Django 4.2.9 on 2024-01-29 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShowType', '0001_initial'),
        ('Movie', '0005_alter_movie_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='showtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='showtype', to='ShowType.showtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG13', 'PG13'), ('13+', '13+'), ('PG16', 'PG16'), ('16+', '16+'), ('17+', '17+'), ('PG18', 'PG18'), ('18+', '18+')], max_length=500),
        ),
    ]
