# Generated by Django 4.2.9 on 2024-01-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created_at', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'ShowTypes',
            },
        ),
    ]
